name: Temporary Studio Hybrid Script

on:
  push:
    branches: [main]
    paths:
      - .github/studio-script-hybrid.trigger

permissions:
  contents: write

jobs:
  script:
    uses: ./.github/workflows/satoshi-studio-module.yml
    with:
      episode: games-as-latent-therapeutics-2026-09-30
      module: script
    secrets: inherit
